### ISSUE TITLE
关于Demo使用问题

### ISSUE THREAD

**Issue by zlhchen** [dotnetcore/surging#156]
下载DEMO后运行Bill.Demo.Services.Server出现如下错误，是log4net组件注册存在问题？还是缺少配置？

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: config
   at Microsoft.Extensions.Options.ConfigurationChangeTokenSource`1..ctor(String name, IConfiguration config)
   at Microsoft.Extensions.Logging.LoggingBuilderExtensions.AddConfiguration(ILoggingBuilder builder, IConfiguration configuration)
   at Surging.Core.Log4net.ServiceHostBuilderExtensions.<>c.<UseLog4net>b__0_0(ILoggingBuilder logger) in E:\技术资料\微服务\Surgings\surging\src\Surging.Core\Surging.Core.Log4net\ServiceHostBuilderExtensions.cs:line 16
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Surging.Core.ServiceHosting.Internal.Implementation.ServiceHostBuilder.Build() in E:\技术资料\微服务\Surgings\surging\src\Surging.Core\Surging.Core.ServiceHosting\Internal\Implementation\ServiceHostBuilder.cs:line 34
   at Bill.Demo.Services.Server.Program.Main(String[] args) in E:\技术资料\微服务\Surgings\SurgingDemo\src\Bill.Demo.Solutions\Bill.Demo.Services.Server\Program.cs:line 24

**Comment by fanliang11** [comment]
surging 已经升级为服务引擎，建议还是看原项目，里面已经有例子了，Demo已经很久未更新，原作者已经不维护了

**Comment by zlhchen** [comment]
好的，谢谢！
