### ISSUE TITLE
运行就报错,是哪设置不对吗?

### ISSUE THREAD

**Issue by gxlqssjf** [dotnetcore/surging#176]
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Surging.Core.Consul.ConsulServiceCacheManager..ctor(ConfigInfo configInfo, ISerializer`1 serializer, ISerializer`1 stringSerializer, IClientWatchManager manager, IServiceCacheFactory serviceCacheFactory, ILogger`1 logger) in G:\SCode\框架\surging\src\Surging.Core\Surging.Core.Consul\ConsulServiceCacheManager.cs:line 43
   at Surging.Core.Consul.ContainerBuilderExtensions.<>c__DisplayClass1_0.<UseConsulCacheManager>b__0(IServiceProvider provider) in G:\SCode\框架\surging\src\Surging.Core\Surging.Core.Consul\ContainerBuilderExtensions.cs:line 41
   at Autofac.Features.LightweightAdapters.LightweightAdapterRegistrationExtensions.<>c__DisplayClass3_0`2.<RegisterAdapter>b__0(IComponentContext c, IEnumerable`1 p, Object f)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)

内部异常 1:
AggregateException: One or more errors occurred.

内部异常 2:
HttpRequestException: 由于目标计算机积极拒绝，无法连接。

内部异常 3:
SocketException: 由于目标计算机积极拒绝，无法连接。

**Comment by fanliang11** [comment]
此错误应该是提示consul无法连接， 请查看consul是否已经启动
