### ISSUE TITLE
最新版本在centos7下运行容器异常退出

### ISSUE THREAD

**Issue by zhouswei** [dotnetcore/surging#213]
Surging.Services.Server 模块在windows 下运行正常，发布到centos7（CentOS Linux release 7.5.1804 (Core)    .netcore 2.1.500 ）后 容器运行异常退出：
异常信息：
Unhandled Exception: System.BadImageFormatException: Bad IL format.
   at Surging.Core.CPlatform.ContainerBuilderExtensions.RegisterServices(IServiceBuilder builder, String[] virtualPaths) in /home/application/surging/surging-master/src/Surging.Core/Surging.Core.CPlatform/ContainerBuilderExtensions.cs:line 522
   at Surging.Core.CPlatform.ContainerBuilderExtensions.AddServiceRuntime(IServiceBuilder builder) in /home/application/surging/surging-master/src/Surging.Core/Surging.Core.CPlatform/ContainerBuilderExtensions.cs:line 402
   at Surging.Services.Server.Program.<>c__DisplayClass0_0.<Main>b__5(IServiceBuilder option) in /home/application/surging/surging-master/src/Surging.Services/Surging.Services.Server/Program.cs:line 39
   at Surging.Core.ServiceHosting.Internal.Implementation.ServiceHostBuilder.RegisterServices() in /home/application/surging/surging-master/src/Surging.Core/Surging.Core.ServiceHosting/Internal/Implementation/ServiceHostBuilder.cs:line 111
   at Surging.Core.ServiceHosting.Internal.Implementation.ServiceHostBuilder.Build() in /home/application/surging/surging-master/src/Surging.Core/Surging.Core.ServiceHosting/Internal/Implementation/ServiceHostBuilder.cs:line 38
   at Surging.Services.Server.Program.Main(String[] args) in /home/application/surging/surging-master/src/Surging.Services/Surging.Services.Server/Program.cs:line 34

**Comment by fanliang11** [comment]
bad il format,请dotnet publish -c release发布模块，和引擎
