### ISSUE TITLE
surging支持netstandard么？

### ISSUE THREAD

**Issue by AaronLucas** [dotnetcore/surging#241]
2019/01/10 20:29:03.679|ERROR|(19,42): error CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. |Surging.Core.ProxyGenerator.Implementation.ServiceProxyGenerater|

**Comment by AaronLucas** [comment]
那如果实现的服务，通过nuget引用第三方的类库，这些类库里面可能是以netstandard（比如说netstandard2.0）生成的，或者其依赖了别的类库是netstandard的，是不是意味着都无法使用Surging?
我现在遇到的问题即使如此。除了吧别人的类库GIT下来，自己改成dotnetcore来生成是不是就没有办法？
另外，你的意思是将来也没有计划支持是吗？

**Comment by AaronLucas** [comment]
补充一下，错误是Client端报出来的，其实我已经在尝试另一种思路（其实是绕过这问题），相对来说算改变最小吧，就是在定义IServiceKey中的接口方法时，使用自定义的 Model，这样改动最小，只是在Server需要对接受到的参数和返回值进行二次封装。提这个问题只是不明白为什么Client进行代理反射时，没有自动加载netstandard（Enum是在netstandard下声明的），并且在我已经加入了
    <PackageReference Include="NETStandard.Library" Version="2.0.3" />后，依然提示没有引用。早就在关注Surging了，但一直也没时间好好学习作者的实现，最近有机会试用才发现此现象，了解的不是很深。

**Comment by fanliang11** [comment]
建议参数来一次Convert,因为引擎只会扫描接口模块，业务模块，SystemModule，BusinessModule，EnginePartModule，你可以按照如下进行设置
### 1.如果不是包含在接口模块或者业务模块，需要标识这个模块的类型。具体参照以下进行设置
[https://github.com/dotnetcore/surging/blob/master/src/Surging.Core/Surging.Core.Common/CommonModule.cs](https://github.com/dotnetcore/surging/blob/master/src/Surging.Core/Surging.Core.Common/CommonModule.cs)
### 2.如果不是包含在接口模块或者业务模块，需要标识特性
```c#
 [DataContract]
```
具体参照以下进行设置
[https://github.com/dotnetcore/surging/blob/master/src/Surging.Core/Surging.Core.Common/ApiResult.cs](https://github.com/dotnetcore/surging/blob/master/src/Surging.Core/Surging.Core.Common/ApiResult.cs)

**Comment by AaronLucas** [comment]
经过测试，我发现，问题可能是发生在枚举上我的测试如下，

IModuleServices
--------------------------------------------------
    //[DataContract]
    [ProtoContract]
    public enum Scope
    {
        [EnumMember]
        dcEnumTest,

        [ProtoEnum]
        protoEnumTest,

        NormalTest
    }

    [ServiceBundle("api/{Service}")]
    public interface IUserService: IServiceKey
    {

        Task<string> Authentication(string userName,string state,Scope scope,string requestUrl = null);

    }
    

Server
--------------------------------------------------
       public class UserService : ProxyServiceBase, IUserService
      {
        public Task<string> Authentication(string userName, string state, Scope scope, string requestUrl = null)
        {
            return Task.FromResult(DateTime.Now.Ticks + requestUrl);
        }
      }

Client
--------------------------------------------------

public class Startup
     {
        /// <summary>
        /// 测试
        /// </summary>
        /// <param name="serviceProxyFactory"></param>
        public static void Test(IServiceProxyFactory serviceProxyFactory)
        {
            Task.Run(async () =>
            {
                var userProxy = serviceProxyFactory.CreateProxy<IUserService>();
                do
                {
                    var watch = Stopwatch.StartNew();
                    for (var i = 0; i < 10000; i++)
                    {
                        var a = await userProxy.Authentication("Aaron", "press", Scope.dcEnumTest);
                        //var a = await userProxy.Authentication("Aaron", "press", Scope.protoEnumTest);
                        //var a = await userProxy.Authentication("Aaron", "press", Scope.NormalTest);
                        Console.WriteLine(a);
                    }
                    watch.Stop();
                    Console.WriteLine($"1w次调用结束，执行时间：{watch.ElapsedMilliseconds}ms");
                    Console.WriteLine("Press any key to continue, q to exit the loop...");
                    var key = Console.ReadLine();
                    if (key.ToLower() == "q")
                        break;

                } while (true);
            }).Wait();
        }


这样调用，现象已经改变，Server在收到请求由SerializerUtilitys反序列化是抛出System.NullReferenceException

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=MessagePack
  StackTrace:
   at MessagePack.Internal.ThreadsafeTypeKeyHashTable`1.TryGetValue(Type key, TValue& value)
   at MessagePack.Internal.ThreadsafeTypeKeyHashTable`1.GetOrAdd(Type key, Func`2 valueFactory)
   at MessagePack.MessagePackSerializer.NonGeneric.GetOrAdd(Type type)
   at MessagePack.MessagePackSerializer.NonGeneric.Deserialize(Type type, Byte[] bytes)
   at Surging.Core.Codec.MessagePack.Utilities.SerializerUtilitys.Deserialize(Byte[] data, Type type) in X:\surging-master.2018.12.19_netcoreapp2.2\surging-master\src\Surging.Core\Surging.Core.Codec.MessagePack\Utilities\SerializerUtilitys.cs:line 28
   at Surging.Core.Codec.MessagePack.Messages.DynamicItem.Get() in X:\surging-master.2018.12.19_netcoreapp2.2\surging-master\src\Surging.Core\Surging.Core.Codec.MessagePack\Messages\DynamicItem.cs:line 62
   at Surging.Core.Codec.MessagePack.Messages.MessagePackRemoteInvokeMessage.<>c.<GetRemoteInvokeMessage>b__26_1(ParameterItem i) in X:\surging-master.2018.12.19_netcoreapp2.2\surging-master\src\Surging.Core\Surging.Core.Codec.MessagePack\Messages\MessagePackRemoteInvokeMessage.cs:line 71
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Surging.Core.Codec.MessagePack.Messages.MessagePackRemoteInvokeMessage.GetRemoteInvokeMessage() in X:\surging-master.2018.12.19_netcoreapp2.2\surging-master\src\Surging.Core\Surging.Core.Codec.MessagePack\Messages\MessagePackRemoteInvokeMessage.cs:line 69
   at Surging.Core.Codec.MessagePack.Messages.MessagePackTransportMessage.GetTransportMessage() in X:\surging-master.2018.12.19_netcoreapp2.2\surging-master\src\Surging.Core\Surging.Core.Codec.MessagePack\Messages\MessagePackTransportMessage.cs:line 68
   at Surging.Core.Codec.MessagePack.MessagePackTransportMessageDecoder.Decode(Byte[] data) in X:\surging-master.2018.12.19_netcoreapp2.2\surging-master\src\Surging.Core\Surging.Core.Codec.MessagePack\MessagePackTransportMessageDecoder.cs:line 15
   at Surging.Core.DotNetty.Adapter.TransportMessageChannelHandlerAdapter.ChannelRead(IChannelHandlerContext context, Object message) in X:\surging-master.2018.12.19_netcoreapp2.2\surging-master\src\Surging.Core\Surging.Core.DotNetty\Adapter\TransportMessageChannelHandlerAdapter.cs:line 27
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelRead(Object msg)

经过查看Client序列化过程，发现是Enum没有被真确序列化（MessagePackRemoteInvokeMessage实现,没有用EnumMessagePackSerializer？），是我实现方式有问题么？因目前为止，还不太清楚Surging是如何利用MessagePack，Protobuf-net,Json的。

    <PackageReference Include="MessagePack" Version="1.7.3.4" />

**Comment by AaronLucas** [comment]
生成 GenerateProxyTree 时没有加入Enum,怎么改？

**Comment by fanliang11** [comment]
我先看看，如果有问题，我这边修改

**Comment by AaronLucas** [comment]
OK
