### ISSUE TITLE
示例中的ApiGateway运行错误

### ISSUE THREAD

**Issue by gxlqssjf** [dotnetcore/surging#280]
![image](https://user-images.githubusercontent.com/1277598/56027788-54e80b80-5d49-11e9-8925-c19ee6b194b4.png)
 at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Surging.Core.Consul.ConsulServiceCacheManager.EnterCaches() in D:\WorkCode\Git\testframe\FrameCode\surging\src\Surging.Core\Surging.Core.Consul\ConsulServiceCacheManager.cs:line 192

![image](https://user-images.githubusercontent.com/1277598/56027775-48fc4980-5d49-11e9-9681-2a93f4785e9a.png)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Surging.Core.Consul.ConsulServiceCacheManager.EnterCaches() in D:\WorkCode\Git\testframe\FrameCode\surging\src\Surging.Core\Surging.Core.Consul\ConsulServiceCacheManager.cs:line 192
![image](https://user-images.githubusercontent.com/1277598/56028042-dd66ac00-5d49-11e9-9257-42d8dc20135d.png)

**Comment by gxlqssjf** [comment]
已经运行了consul
![image](https://user-images.githubusercontent.com/1277598/56028134-1141d180-5d4a-11e9-95c9-e61ab7a052e8.png)

**Comment by fanliang11** [comment]
不解答运行不了的问题，请自己解决
