### ISSUE TITLE
服务之间调用的时候，会报错。

### ISSUE THREAD

**Issue by yxl0173** [dotnetcore/surging#37]
public Task<string> GetUserName(int id)
        {
            Console.WriteLine("被调用");

            StartRequest1();

            return Task.FromResult($"id:{id} is name fanly.");
        }

        private static void StartRequest1()
        {

            var service = ServiceLocator.GetService<IServiceProxyFactory>();
            var userProxy = service.CreateProxy<IUser2Service>();
            var ss = userProxy.GetUserName(123);
            Console.WriteLine(ss);

        }

2018-01-04 13:25:09,225 [32] ERROR Surging.Core.CPlatform.Runtime.Server.Implementation.DefaultServiceExecutor [(null)] - 执行本地逻辑时候发生了错误。
Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'Surging.Core.ProxyGenerator.IServiceProxyFactory' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Surging.Core.CPlatform.Utilities.ServiceLocator.GetService[T]() in D:\Users\yxl2016\Desktop\surging-master\src\Surging.Core\Surging.Core.CPlatform\Utilities\ServiceLocator.cs:line 12
   at Surging.Modules.Common.Domain.UserService.StartRequest1() in D:\Users\yxl2016\Desktop\surging-master\src\Surging.Modules\Surging.Modules.Common\Domain\UserService.cs:line 32
   at Surging.Modules.Common.Domain.UserService.GetUserName(Int32 id) in D:\Users\yxl2016\Desktop\surging-master\src\Surging.Modules\Surging.Modules.Common\Domain\UserService.cs:line 23
   at (Object , Object[] )
   at Surging.Core.CPlatform.Runtime.Server.Implementation.ServiceDiscovery.Implementation.ClrServiceEntryFactory.<>c__DisplayClass5_0.<Create>b__1(String key, IDictionary`2 parameters)
   at Surging.Core.CPlatform.Runtime.Server.Implementation.DefaultServiceExecutor.<LocalExecuteAsync>d__6.MoveNext()

**Comment by fanliang11** [comment]
用this.GetService<IUser2Service>().GetUserName(123);

**Comment by fanliang11** [comment]
用this.GetService<IUser2Service>().GetUserName(123);

**Comment by fanliang11** [comment]
还有服务端如果要使用远程代理调用请加Program.cs文件中增加以下配置
```c#
   .RegisterServices(builder =>
                {
                    builder.AddMicroService(option =>
                    {
                        option.AddServiceRuntime();

                        option.AddClientProxy();//添加支持服务代理
                        //option.UseZooKeeperManager(new ConfigInfo("127.0.0.1:2181"));
                        option.UseConsulManager(new ConfigInfo("127.0.0.1:8500"));
                        option.UseDotNettyTransport();
                        option.UseRabbitMQTransport();
                        option.AddRabbitMQAdapt();
                        //option.UseProtoBufferCodec();
                        option.UseMessagePackCodec();
                        builder.Register(p => new CPlatformContainer(ServiceLocator.Current));
                    });
                })
```

**Comment by fanliang11** [comment]
```c#
this.GetService<IUser2Service>().GetUserName(123);
```
使用以上代码，就算是在同一程序中的服务，后面要拆分成各个微服务，也不会产生问题，因为支持本地和远程调用。

**Comment by fanliang11** [comment]
option.AddRelateService()//添加支持服务代理远程调用

**Comment by SkipperGuo** [comment]
请问作者 option.AddRelateService() 在nuget 0.4.9.2 的版本中有这个方法吗？因为 我在这个版本中 这个方法是报错的

**Comment by fanliang11** [comment]
因为是昨天修改，还没有发布到nuget，今天发布0.4.9.3版本

**Comment by yxl0173** [comment]
现在已经可以了。没问题了。感谢。
