### ISSUE TITLE
运行案例出现异常

### ISSUE THREAD

**Issue by sunriseyuen** [dotnetcore/surging#64]
Unhandled Exception: System.AggregateException: One or more errors occurred. (Value cannot be null.
Parameter name: serviceKey) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: serviceKey
   at Autofac.Core.KeyedService..ctor(Object serviceKey, Type serviceType)
   at Autofac.ResolutionExtensions.IsRegisteredWithKey[TService](IComponentContext context, Object serviceKey)
   at Surging.Core.CPlatform.CPlatformContainer.IsRegistered[T](Object serviceKey) in C:\proj\surging\src\Surging.Core\Surging.Core.CPlatform\CPlatformContainer.cs:line 25
   at Surging.Core.ProxyGenerator.Implementation.ServiceProxyBase.<Invoke>d__8`1.MoveNext() in C:\proj\surging\src\Surging.Core\Surging.Core.ProxyGenerator\Implementation\ServiceProxyBase.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Surging.Cores.ClientProxys.UserServiceClientProxy.<GetUserId>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Surging.Services.Client.Startup.<>c__DisplayClass7_0.<<Test>b__0>d.MoveNext() in C:\proj\surging\src\Surging.Services\Surging.Services.Client\Startup.cs:line 83
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Surging.Services.Client.Startup.Test(IServiceProxyFactory serviceProxyFactory) in C:\proj\surging\src\Surging.Services\Surging.Services.Client\Startup.cs:line 75
   at Surging.Services.Client.Program.Main(String[] args) in C:\proj\surging\src\Surging.Services\Surging.Services.Client\Program.cs:line 74

**Comment by fanliang11** [comment]
serviceKey 为null导致的
如果设置了ModuleName，就需要传serviceKey
