### ISSUE TITLE
多个服务端相互调用

### ISSUE THREAD

**Issue by jakcm** [dotnetcore/surging#67]
我想在SurgingAbpMicroservice服务里面，调用MicroserviceService1的服务。
也就是SurgingAbpMicroservice既作为服务端，也作为客户端，加了AddClient：
![2](https://user-images.githubusercontent.com/38003884/39054278-c850039a-44e3-11e8-9d0b-7d4575e92ead.png)

启动SurgingAbpMicroservice服务的时候报错：
Autofac.Core.DependencyResolutionException
  HResult=0x80131500
  Message=An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = Object (DelegateActivator), Services = [Surging.Core.CPlatform.Support.IServiceCommandManager], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope
  Source=Autofac
  StackTrace:
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Surging.Core.CPlatform.ServiceHostBuilderExtensions.<>c__DisplayClass0_0.<UseServer>b__0(IContainer mapper)
   at Surging.Core.ServiceHosting.Internal.Implementation.ServiceHost.MapperServices(IContainer mapper)
   at Surging.Core.ServiceHosting.Internal.Implementation.ServiceHost.Run() 
   at SurgingAbpMicroservice.Service.Program.Main(String[] args) 

内部异常 1:
DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = DefaultServiceEntryManager (ReflectionActivator), Services = [Surging.Core.CPlatform.Runtime.Server.IServiceEntryManager], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope

内部异常 2:
DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(System.Collections.Generic.IEnumerable`1[Surging.Core.CPlatform.Runtime.Server.IServiceEntryProvider])' on type 'DefaultServiceEntryManager'.

内部异常 3:
InvalidOperationException: 本地包含多个Id为：MicroserviceService1.IService.ITestMoneyS001Service.GetDailyMoneyList 的服务条目。

**Comment by ming2882** [comment]
.服务与服务之间的调用，请使用抽象父类ProxyServiceBase的GetService()
一个服务调用另一个服务的接口，会在Consul中生成两个IP和端口，这时不会出问题吗，我试过有问题的，AddressSelectorBase会取IP：Port一条没实现的，运气好会取到有服务实现。
