### ISSUE TITLE
dotnetty输出错误

### ISSUE THREAD

**Issue by victor596** [dotnetcore/surging#77]
大牛,你好。我的surging在一台WIN10上运行，每次客户端连接一次服务端都产生一个错误.

ERROR Surging.Core.DotNetty.DotNettyServerMessageListener [(null)] - 与服务器：[::ffff:172.16.3.70]:40096通信时发送了错误。
System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   at DotNetty.Transport.Channels.Sockets.SocketChannelAsyncOperation.Validate()
   at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)

**Comment by fanliang11** [comment]
应该是服务端捕捉不正常关闭的错误。

**Comment by victor596** [comment]
客户端也就这样使用，没什么特别的
 var service = ServiceLocator.GetService<IServiceProxyFactory>();
            var userProxy = service.CreateProxy<IUserService>("User");
            DateTime curr = DateTime.Now;
            List<Task> tasks = new List<Task>();
            for (int i = 0; i <= 100; i++)
            {
                tasks.Add(userProxy.GetAllUsers());
            }
            Task.WaitAll(tasks.ToArray());
            Console.WriteLine(DateTime.Now.Subtract(curr).TotalSeconds);

**Comment by firstrose** [comment]
> 因为执行完，会和服务端断开链接，所以服务端会捕获不正常关闭的错误

我也碰到同样的问题。请问你的这段话该怎么理解？是不是用ServiceLocator调用的时候，客户端实际上是作为一个微服务和服务端通信，而微服务之间通信肯定就是走DotNetty，导致连接断开被统一识别为非正常关闭？
